package com.company;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import com.company.DefaultBinaryTree;
import com.company.BinaryTree;
import com.company.utils.ArrayUtils;
import com.company.utils.SwingUtils;
import com.company.DefaultBSTree;

public class JFrame extends javax.swing.JFrame {

    DefaultBinaryTree<Integer> tree = new BinaryTree<>();

    private JPanel paintPanel = null;

    /**
     * Creates new form MainJFrame
     */

    public JFrame() {
        initComponents();
        paintAreaJPanel.setLayout(new BorderLayout());
        paintPanel = new JPanel() {
            @Override
            public void paintComponent(Graphics gr) {
                super.paintComponent(gr);
                Point size = BinaryTreePainter.paint(tree, gr);
                SwingUtils.setFixedSize(paintPanel, size.x, size.y);
            }
        };
        JScrollPane paintJScrollPane = new JScrollPane(paintPanel);
        paintAreaJPanel.add(paintJScrollPane);
        //SwingUtils.setFixedSize(paintPanel, 5000, 2000);
        mainJSplitPane.setDividerLocation(0.5);
        mainJSplitPane.setResizeWeight(1.0);
    }

    public void repaintTree() {
        paintPanel.repaint();
    }

    private void showSystemOut(Runnable action) {
        PrintStream oldOut = System.out;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            System.setOut(new PrintStream(baos, true, "UTF-8"));

            action.run();

            systemOutJTextArea.setText(baos.toString("UTF-8"));
        } catch (UnsupportedEncodingException impossible) {
        }
        System.setOut(oldOut);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mainJSplitPane = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        addJButton = new javax.swing.JButton();
        makeBSTreeJButton2 = new javax.swing.JButton();
        bracketNotationJTextField = new javax.swing.JTextField();
        makeRBTreeJButton = new javax.swing.JButton();
        valuesJTextField = new javax.swing.JTextField();
        removeJButton = new javax.swing.JButton();
        addValueJTextArea = new javax.swing.JTextField();
        makeTreeJButton = new javax.swing.JButton();
        valuesJLabel = new javax.swing.JLabel();
        makeAVLTreeJButton = new javax.swing.JButton();
        paintAreaJPanel = new javax.swing.JPanel();
        randomJLabel = new javax.swing.JLabel();
        randomCountJSpinner = new javax.swing.JSpinner();
        randomGenerateJButton = new javax.swing.JButton();
        sortValuesJButton = new javax.swing.JButton();
        makeBSTreeJButton1 = new javax.swing.JButton();
        rightJPanel = new javax.swing.JPanel();
        preOrderTraversJButton = new javax.swing.JButton();
        inOrderTraversJButton = new javax.swing.JButton();
        postOrderTraversJButton = new javax.swing.JButton();
        byLevelTraversJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemOutJTextArea = new javax.swing.JTextArea();
        mainJMenuBar = new javax.swing.JMenuBar();
        testingJMenu = new javax.swing.JMenu();
        correctTestSimpleBSTreeMapJMenuItem = new javax.swing.JMenuItem();
        correctTestAVLTreeMapJMenuItem = new javax.swing.JMenuItem();
        correctTestRBTreeMapJMenuItem = new javax.swing.JMenuItem();
        minJButton = new javax.swing.JButton();


        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Операции с деревьями");

        mainJSplitPane.setBorder(null);

        addJButton.setText("Добавить");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        bracketNotationJTextField.setText("8 (6 (4 (,5), 6), 5 (, 5 (2, 8)))");

        valuesJTextField.setText("6, 8, 3, 5, 7, 2, 16, 1, 15, 12, 9");

        removeJButton.setText("Удалить");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        addValueJTextArea.setText("10");

        makeTreeJButton.setText("Построить дерево");
        makeTreeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTreeJButtonActionPerformed(evt);
            }
        });

        valuesJLabel.setText("Значения для построения дерева:");

        paintAreaJPanel.setLayout(new javax.swing.BoxLayout(paintAreaJPanel, javax.swing.BoxLayout.LINE_AXIS));

        randomJLabel.setText("случайных чисел");

        randomCountJSpinner.setModel(new javax.swing.SpinnerNumberModel(30, null, null, 1));

        randomGenerateJButton.setText("Сгенерировать");
        randomGenerateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomGenerateJButtonActionPerformed(evt);
            }
        });

        sortValuesJButton.setText("Упорядочить");
        sortValuesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortValuesJButtonActionPerformed(evt);
            }
        });
        minJTextField = new javax.swing.JTextField();
        minJButton.setText("Найти минимальный элемент");
        minJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinaryTree<Integer> tree = new BinaryTree<>(s -> Integer.parseInt(s));
                String temp = null;
                try {
                    temp = String.valueOf(tree.findingMin(bracketNotationJTextField.getText()));
                } catch (Exception e) {
                    e.printStackTrace();
                }
                minJTextField.setText(temp);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
                leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(leftJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(valuesJTextField)
                                        .addComponent(bracketNotationJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(paintAreaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(leftJPanelLayout.createSequentialGroup()
                                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(valuesJLabel)
                                                        .addGroup(leftJPanelLayout.createSequentialGroup()
                                                                .addComponent(addValueJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(minJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(addJButton)
                                                                .addComponent(minJButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(removeJButton))
                                                        .addGroup(leftJPanelLayout.createSequentialGroup()
                                                                .addComponent(makeTreeJButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(makeBSTreeJButton1))
                                                        .addGroup(leftJPanelLayout.createSequentialGroup()
                                                                .addComponent(makeBSTreeJButton2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(makeAVLTreeJButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(makeRBTreeJButton))
                                                        .addGroup(leftJPanelLayout.createSequentialGroup()
                                                                .addComponent(randomCountJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(randomJLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(randomGenerateJButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sortValuesJButton)))
                                                .addGap(0, 2, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        leftJPanelLayout.setVerticalGroup(
                leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(valuesJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bracketNotationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(makeTreeJButton)
                                        .addComponent(makeBSTreeJButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valuesJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(randomJLabel)
                                        .addComponent(randomCountJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(randomGenerateJButton)
                                        .addComponent(sortValuesJButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(makeAVLTreeJButton)
                                        .addComponent(makeRBTreeJButton)
                                        .addComponent(makeBSTreeJButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addJButton)
                                        .addComponent(minJButton)
                                        .addComponent(minJTextField,javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addValueJTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(removeJButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paintAreaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addContainerGap())
        );

        mainJSplitPane.setLeftComponent(leftJPanel);

        systemOutJTextArea.setColumns(20);
        systemOutJTextArea.setRows(5);
        jScrollPane1.setViewportView(systemOutJTextArea);

        javax.swing.GroupLayout rightJPanelLayout = new javax.swing.GroupLayout(rightJPanel);
        rightJPanel.setLayout(rightJPanelLayout);
        rightJPanelLayout.setHorizontalGroup(
                rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rightJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(rightJPanelLayout.createSequentialGroup()
                                                .addGroup(rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(postOrderTraversJButton)
                                                        .addComponent(preOrderTraversJButton)
                                                        .addComponent(inOrderTraversJButton)
                                                        .addComponent(byLevelTraversJButton))
                                                .addGap(0, 89, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );
        rightJPanelLayout.setVerticalGroup(
                rightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rightJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(preOrderTraversJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inOrderTraversJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postOrderTraversJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(byLevelTraversJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addContainerGap())
        );

        mainJSplitPane.setRightComponent(rightJPanel);

        testingJMenu.setText("Тестирование");

        mainJMenuBar.add(testingJMenu);

        setJMenuBar(mainJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainJSplitPane)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainJSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void makeTreeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTreeJButtonActionPerformed
        try {
            BinaryTree<Integer> tree = new BinaryTree<>(s -> Integer.parseInt(s));
            tree.fromBracketNotation(bracketNotationJTextField.getText());
            this.tree = tree;
            repaintTree();
        } catch (Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_makeTreeJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        if (!(tree instanceof DefaultBSTree)) {
            SwingUtils.showInfoMessageBox("Текущее дерево не является деревом поиска!");
            return;
        }
        try {
            ((DefaultBSTree<Integer>) tree).remove(Integer.parseInt(addValueJTextArea.getText()));
            repaintTree();
        } catch (Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_removeJButtonActionPerformed

    //
    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        if (!(tree instanceof DefaultBSTree)) {
            SwingUtils.showInfoMessageBox("Текущее дерево не является деревом поиска!");
            return;
        }
        try {
            ((DefaultBSTree<Integer>) tree).put(Integer.parseInt(addValueJTextArea.getText()));
            repaintTree();
        } catch (Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void randomGenerateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomGenerateJButtonActionPerformed
        int size = ((Integer) randomCountJSpinner.getValue()).intValue();
        int[] arr = ArrayUtils.createRandomIntArray(size, (size <= 50) ? 100 : 1000);
        valuesJTextField.setText(ArrayUtils.toString(arr));
    }//GEN-LAST:event_randomGenerateJButtonActionPerformed

    private void sortValuesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortValuesJButtonActionPerformed
        try {
            int[] arr = ArrayUtils.toIntArray(valuesJTextField.getText());
            Arrays.sort(arr);
            valuesJTextField.setText(ArrayUtils.toString(arr));
        } catch (Exception ex) {
            SwingUtils.showErrorMessageBox(ex);
        }
    }//GEN-LAST:event_sortValuesJButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTextField addValueJTextArea;
    private javax.swing.JTextField bracketNotationJTextField;
    private javax.swing.JButton byLevelTraversJButton;
    private javax.swing.JMenuItem correctTestAVLTreeMapJMenuItem;
    private javax.swing.JMenuItem correctTestRBTreeMapJMenuItem;
    private javax.swing.JMenuItem correctTestSimpleBSTreeMapJMenuItem;
    private javax.swing.JButton inOrderTraversJButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JMenuBar mainJMenuBar;
    private javax.swing.JSplitPane mainJSplitPane;
    private javax.swing.JButton makeAVLTreeJButton;
    private javax.swing.JButton makeBSTreeJButton1;
    private javax.swing.JButton makeBSTreeJButton2;
    private javax.swing.JButton makeRBTreeJButton;
    private javax.swing.JButton makeTreeJButton;
    private javax.swing.JPanel paintAreaJPanel;
    private javax.swing.JButton postOrderTraversJButton;
    private javax.swing.JButton preOrderTraversJButton;
    private javax.swing.JSpinner randomCountJSpinner;
    private javax.swing.JButton randomGenerateJButton;
    private javax.swing.JLabel randomJLabel;
    private javax.swing.JButton removeJButton;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JButton sortValuesJButton;
    private javax.swing.JTextArea systemOutJTextArea;
    private javax.swing.JMenu testingJMenu;
    private javax.swing.JLabel valuesJLabel;
    private javax.swing.JTextField valuesJTextField;
    private javax.swing.JButton minJButton;
    private javax.swing.JTextField minJTextField;
    // End of variables declaration//GEN-END:variables
}
